### PR TITLE
Upgrade source code to Delft3D tag 65936

### PR DESCRIPTION
**Pull request by H0R5E**
This PR updates the source code in this repository to tag 65936 on the Delft3D SVN repo (the recommended tag for Delft3D4). I have tested an x64 windows build against the tutorial example and here is the result:

x64

This matches well with a run using the old binaries, as shown here:

win32

I hadn't ported over the TKE code when I first opened this PR, hence the differences show in my original image:

x64

Note that the turbine code does not run correctly for turbine cases in MPI parallel, but I *think* that is expected.

I have not updated (or added) more binaries. My recommendation would be to attach binaries to a release, rather than add them to the source repository, so that the repo history does not become extremely large. I'll open an issue with this suggestion.

The reason that so many files are changed is because I removed all of the compilation folders that were left in the source code in the original commit. This PR reduces the files down to those needed for compilation. Also 65936 has many more external packages included.

### CODE REVIEW

**Comment by H0R5E** [comment]
I'm just upgrading and checking the shipped examples.

**Comment by H0R5E** [comment]
All examples are working except for the parallel run using the turbines. I get this error in each of the threads:

```
 *** ERROR Velocity reference point primary side outside domain for turbine: My 
 First Turbine
```

I will try to find out if this is something I have done incorrectly.

**Comment by H0R5E** [comment]
So, I found a long list in the manual of cases that don't run with the MPI parallelisation, as follows:

> ### MPI-based parallel
> 
> Example scripts are inside https://svn.oss.deltares.nl/repos/delft3d/trunk/examples/01_standard.  The domain is split automatically in stripwise partitions.
> *   Can not be started via Delft3D-MENU
> *   Does not work in combination with:
>     +   DomainDecomposition
>     +   Fluid mud
>     +   Coup online
>     +   Drogues and moving observation points
>     +   Culverts
>     +   Power stations with inlet and outlet in different partitions
>     +   Non-hydrostatic solvers
>     +   Walking discharges
>     +   2D skewed weirs
>     +   max(mmax,nmax)/npart <= 4
>     +   Roller model
>     +   Mormerge
>     +   Mass balance polygons

I'm just going to assume that the turbines code fits into the same category.

**Comment by H0R5E** [comment]
OK, this is ready to go now. See the updated first post for info.

**Comment by Mamba0803** [comment]
Hello sir, your video has been very useful to me and I have made the most of your instructions... but it saddens me that I cannot run the software due to an error that appears like this: 
Flow exited abnormally
 Check diagnosis file
ABORT in FLOW2D3D: An exception occurred
child process exited abnormally     
I hope to be able to contact you to receive your help in advance, very grateful

**Pull request closed without merging**
